/* Generated By:JavaCC: Do not edit this line. AnalizerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int let = 5;
  /** RegularExpression Id. */
  int dig = 6;
  /** RegularExpression Id. */
  int gui = 7;
  /** RegularExpression Id. */
  int pun = 8;
  /** RegularExpression Id. */
  int arr = 9;
  /** RegularExpression Id. */
  int SBAJO = 10;
  /** RegularExpression Id. */
  int SALTO = 11;
  /** RegularExpression Id. */
  int Usuario = 12;
  /** RegularExpression Id. */
  int Expresion = 13;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<let>",
    "<dig>",
    "\"_\"",
    "\".\"",
    "\"@\"",
    "<SBAJO>",
    "<SALTO>",
    "<Usuario>",
    "<Expresion>",
  };

}
